Reapply "Fix Event.h variable names"
This reverts commit 97f0fef83d8ab9fd43c628867273a4b753de63ef.

... to avoid errors like

   /host/testlibs/Event.h:80:33: error: declaration of ‘Event::KeyEvent
   Event::<unnamed union>::Key’ changes meaning of ‘Key’ [-Wchanges-
   ...
   /host/testlibs/Event.h:30:9: note: used here to mean ‘enum Key’
   30 |         Key Code;
      |         ^~~

Bug: n/a
Test: cd hardware/google/gfxstream
      mkdir build
      cd build
      cmake .. -G Ninja
      ninja
Change-Id: Ie420aa2166db2ee09efea660b49b3e132a39c72f